// src/store/transportation/actionTypes.js

// Companies
export const GET_TRANSPORTATION_COMPANIES = "GET_TRANSPORTATION_COMPANIES";
export const GET_TRANSPORTATION_COMPANIES_SUCCESS =
  "GET_TRANSPORTATION_COMPANIES_SUCCESS";
export const GET_TRANSPORTATION_COMPANIES_FAIL =
  "GET_TRANSPORTATION_COMPANIES_FAIL";

export const CREATE_TRANSPORTATION_COMPANY = "CREATE_TRANSPORTATION_COMPANY";
export const CREATE_TRANSPORTATION_COMPANY_SUCCESS =
  "CREATE_TRANSPORTATION_COMPANY_SUCCESS";
export const CREATE_TRANSPORTATION_COMPANY_FAIL =
  "CREATE_TRANSPORTATION_COMPANY_FAIL";

export const GET_TRANSPORTATION_COMPANY = "GET_TRANSPORTATION_COMPANY";
export const GET_TRANSPORTATION_COMPANY_SUCCESS =
  "GET_TRANSPORTATION_COMPANY_SUCCESS";
export const GET_TRANSPORTATION_COMPANY_FAIL =
  "GET_TRANSPORTATION_COMPANY_FAIL";

export const UPDATE_TRANSPORTATION_COMPANY = "UPDATE_TRANSPORTATION_COMPANY";
export const UPDATE_TRANSPORTATION_COMPANY_SUCCESS =
  "UPDATE_TRANSPORTATION_COMPANY_SUCCESS";
export const UPDATE_TRANSPORTATION_COMPANY_FAIL =
  "UPDATE_TRANSPORTATION_COMPANY_FAIL";

export const DELETE_TRANSPORTATION_COMPANY = "DELETE_TRANSPORTATION_COMPANY";
export const DELETE_TRANSPORTATION_COMPANY_SUCCESS =
  "DELETE_TRANSPORTATION_COMPANY_SUCCESS";
export const DELETE_TRANSPORTATION_COMPANY_FAIL =
  "DELETE_TRANSPORTATION_COMPANY_FAIL";

// Contracts
export const GET_TRANSPORTATION_CONTRACTS = "GET_TRANSPORTATION_CONTRACTS";
export const GET_TRANSPORTATION_CONTRACTS_SUCCESS =
  "GET_TRANSPORTATION_CONTRACTS_SUCCESS";
export const GET_TRANSPORTATION_CONTRACTS_FAIL =
  "GET_TRANSPORTATION_CONTRACTS_FAIL";

export const CREATE_TRANSPORTATION_CONTRACT = "CREATE_TRANSPORTATION_CONTRACT";
export const CREATE_TRANSPORTATION_CONTRACT_SUCCESS =
  "CREATE_TRANSPORTATION_CONTRACT_SUCCESS";
export const CREATE_TRANSPORTATION_CONTRACT_FAIL =
  "CREATE_TRANSPORTATION_CONTRACT_FAIL";

export const UPDATE_TRANSPORTATION_CONTRACT = "UPDATE_TRANSPORTATION_CONTRACT";
export const UPDATE_TRANSPORTATION_CONTRACT_SUCCESS =
  "UPDATE_TRANSPORTATION_CONTRACT_SUCCESS";
export const UPDATE_TRANSPORTATION_CONTRACT_FAIL =
  "UPDATE_TRANSPORTATION_CONTRACT_FAIL";

export const DELETE_TRANSPORTATION_CONTRACT = "DELETE_TRANSPORTATION_CONTRACT";
export const DELETE_TRANSPORTATION_CONTRACT_SUCCESS =
  "DELETE_TRANSPORTATION_CONTRACT_SUCCESS";
export const DELETE_TRANSPORTATION_CONTRACT_FAIL =
  "DELETE_TRANSPORTATION_CONTRACT_FAIL";

// Vehicles
export const GET_TRANSPORTATION_VEHICLES = "GET_TRANSPORTATION_VEHICLES";
export const GET_TRANSPORTATION_VEHICLES_SUCCESS =
  "GET_TRANSPORTATION_VEHICLES_SUCCESS";
export const GET_TRANSPORTATION_VEHICLES_FAIL =
  "GET_TRANSPORTATION_VEHICLES_FAIL";

export const CREATE_TRANSPORTATION_VEHICLE = "CREATE_TRANSPORTATION_VEHICLE";
export const CREATE_TRANSPORTATION_VEHICLE_SUCCESS =
  "CREATE_TRANSPORTATION_VEHICLE_SUCCESS";
export const CREATE_TRANSPORTATION_VEHICLE_FAIL =
  "CREATE_TRANSPORTATION_VEHICLE_FAIL";

export const UPDATE_TRANSPORTATION_VEHICLE = "UPDATE_TRANSPORTATION_VEHICLE";
export const UPDATE_TRANSPORTATION_VEHICLE_SUCCESS =
  "UPDATE_TRANSPORTATION_VEHICLE_SUCCESS";
export const UPDATE_TRANSPORTATION_VEHICLE_FAIL =
  "UPDATE_TRANSPORTATION_VEHICLE_FAIL";

export const DELETE_TRANSPORTATION_VEHICLE = "DELETE_TRANSPORTATION_VEHICLE";
export const DELETE_TRANSPORTATION_VEHICLE_SUCCESS =
  "DELETE_TRANSPORTATION_VEHICLE_SUCCESS";
export const DELETE_TRANSPORTATION_VEHICLE_FAIL =
  "DELETE_TRANSPORTATION_VEHICLE_FAIL";

// UI
export const CLEAR_TRANSPORTATION_MESSAGES = "CLEAR_TRANSPORTATION_MESSAGES";
