export const GET_EXTRA_SERVICES = "GET_EXTRA_SERVICES";
export const GET_EXTRA_SERVICES_SUCCESS = "GET_EXTRA_SERVICES_SUCCESS";
export const GET_EXTRA_SERVICES_FAIL = "GET_EXTRA_SERVICES_FAIL";

export const GET_QUOTATION_EXTRA_SERVICES = "GET_QUOTATION_EXTRA_SERVICES";
export const GET_QUOTATION_EXTRA_SERVICES_SUCCESS =
  "GET_QUOTATION_EXTRA_SERVICES_SUCCESS";
export const GET_QUOTATION_EXTRA_SERVICES_FAIL =
  "GET_QUOTATION_EXTRA_SERVICES_FAIL";

export const SAVE_QUOTATION_EXTRA_SERVICE = "SAVE_QUOTATION_EXTRA_SERVICE";
export const SAVE_QUOTATION_EXTRA_SERVICE_SUCCESS =
  "SAVE_QUOTATION_EXTRA_SERVICE_SUCCESS";
export const SAVE_QUOTATION_EXTRA_SERVICE_FAIL =
  "SAVE_QUOTATION_EXTRA_SERVICE_FAIL";

export const DELETE_QUOTATION_EXTRA_SERVICE = "DELETE_QUOTATION_EXTRA_SERVICE";
export const DELETE_QUOTATION_EXTRA_SERVICE_SUCCESS =
  "DELETE_QUOTATION_EXTRA_SERVICE_SUCCESS";
export const DELETE_QUOTATION_EXTRA_SERVICE_FAIL =
  "DELETE_QUOTATION_EXTRA_SERVICE_FAIL";

export const CLEAR_STEP3_MESSAGES = "CLEAR_STEP3_MESSAGES";
