// LIST
export const GET_RESTAURANTS = "GET_RESTAURANTS";
export const GET_RESTAURANTS_SUCCESS = "GET_RESTAURANTS_SUCCESS";
export const GET_RESTAURANTS_FAIL = "GET_RESTAURANTS_FAIL";

// SINGLE
export const GET_RESTAURANT = "GET_RESTAURANT";
export const GET_RESTAURANT_SUCCESS = "GET_RESTAURANT_SUCCESS";
export const GET_RESTAURANT_FAIL = "GET_RESTAURANT_FAIL";

// CRUD
export const CREATE_RESTAURANT = "CREATE_RESTAURANT";
export const CREATE_RESTAURANT_SUCCESS = "CREATE_RESTAURANT_SUCCESS";
export const CREATE_RESTAURANT_FAIL = "CREATE_RESTAURANT_FAIL";

export const UPDATE_RESTAURANT = "UPDATE_RESTAURANT";
export const UPDATE_RESTAURANT_SUCCESS = "UPDATE_RESTAURANT_SUCCESS";
export const UPDATE_RESTAURANT_FAIL = "UPDATE_RESTAURANT_FAIL";

export const DELETE_RESTAURANT = "DELETE_RESTAURANT";
export const DELETE_RESTAURANT_SUCCESS = "DELETE_RESTAURANT_SUCCESS";
export const DELETE_RESTAURANT_FAIL = "DELETE_RESTAURANT_FAIL";

// UI
export const CLEAR_RESTAURANTS_MESSAGES = "CLEAR_RESTAURANTS_MESSAGES";
