export const GET_ROUTES = "GET_ROUTES";
export const GET_ROUTES_SUCCESS = "GET_ROUTES_SUCCESS";
export const GET_ROUTES_FAIL = "GET_ROUTES_FAIL";

export const GET_ROUTE = "GET_ROUTE";
export const GET_ROUTE_SUCCESS = "GET_ROUTE_SUCCESS";
export const GET_ROUTE_FAIL = "GET_ROUTE_FAIL";

export const CREATE_ROUTE = "CREATE_ROUTE";
export const CREATE_ROUTE_SUCCESS = "CREATE_ROUTE_SUCCESS";
export const CREATE_ROUTE_FAIL = "CREATE_ROUTE_FAIL";

export const GET_PLACES = "GET_PLACES";
export const GET_PLACES_SUCCESS = "GET_PLACES_SUCCESS";
export const GET_PLACES_FAIL = "GET_PLACES_FAIL";

export const CLEAR_ROUTES_MESSAGES = "CLEAR_ROUTES_MESSAGES";
