// src/store/SystemLists/actionTypes.js

export const GET_SYSTEM_LISTS = "GET_SYSTEM_LISTS";
export const GET_SYSTEM_LISTS_SUCCESS = "GET_SYSTEM_LISTS_SUCCESS";
export const GET_SYSTEM_LISTS_FAIL = "GET_SYSTEM_LISTS_FAIL";

export const GET_SYSTEM_LIST_ITEMS = "GET_SYSTEM_LIST_ITEMS";
export const GET_SYSTEM_LIST_ITEMS_SUCCESS = "GET_SYSTEM_LIST_ITEMS_SUCCESS";
export const GET_SYSTEM_LIST_ITEMS_FAIL = "GET_SYSTEM_LIST_ITEMS_FAIL";

export const CREATE_SYSTEM_LIST_ITEM = "CREATE_SYSTEM_LIST_ITEM";
export const CREATE_SYSTEM_LIST_ITEM_SUCCESS =
  "CREATE_SYSTEM_LIST_ITEM_SUCCESS";
export const CREATE_SYSTEM_LIST_ITEM_FAIL = "CREATE_SYSTEM_LIST_ITEM_FAIL";

export const UPDATE_SYSTEM_LIST_ITEM = "UPDATE_SYSTEM_LIST_ITEM";
export const UPDATE_SYSTEM_LIST_ITEM_SUCCESS =
  "UPDATE_SYSTEM_LIST_ITEM_SUCCESS";
export const UPDATE_SYSTEM_LIST_ITEM_FAIL = "UPDATE_SYSTEM_LIST_ITEM_FAIL";
export const GET_SYSTEM_LIST_ITEMS_BY_ID = "GET_SYSTEM_LIST_ITEMS_BY_ID";
