export const GET_GUIDES = "GET_GUIDES";
export const GET_GUIDES_SUCCESS = "GET_GUIDES_SUCCESS";
export const GET_GUIDES_FAIL = "GET_GUIDES_FAIL";

export const GET_GUIDE = "GET_GUIDE";
export const GET_GUIDE_SUCCESS = "GET_GUIDE_SUCCESS";
export const GET_GUIDE_FAIL = "GET_GUIDE_FAIL";

export const CREATE_GUIDE = "CREATE_GUIDE";
export const CREATE_GUIDE_SUCCESS = "CREATE_GUIDE_SUCCESS";
export const CREATE_GUIDE_FAIL = "CREATE_GUIDE_FAIL";

export const UPDATE_GUIDE = "UPDATE_GUIDE";
export const UPDATE_GUIDE_SUCCESS = "UPDATE_GUIDE_SUCCESS";
export const UPDATE_GUIDE_FAIL = "UPDATE_GUIDE_FAIL";

export const DELETE_GUIDE = "DELETE_GUIDE";
export const DELETE_GUIDE_SUCCESS = "DELETE_GUIDE_SUCCESS";
export const DELETE_GUIDE_FAIL = "DELETE_GUIDE_FAIL";

export const CLEAR_GUIDES_MESSAGES = "CLEAR_GUIDES_MESSAGES";
