export const GET_QOUTATIONS = "GET_QOUTATIONS";
export const GET_QOUTATIONS_SUCCESS = "GET_QOUTATIONS_SUCCESS";
export const GET_QOUTATIONS_FAIL = "GET_QOUTATIONS_FAIL";

export const CREATE_QOUTATION = "CREATE_QOUTATION";
export const CREATE_QOUTATION_SUCCESS = "CREATE_QOUTATION_SUCCESS";
export const CREATE_QOUTATION_FAIL = "CREATE_QOUTATION_FAIL";

export const CLEAR_QOUTATIONS_MESSAGES = "CLEAR_QOUTATIONS_MESSAGES";


export const GET_QOUTATION_BY_ID = "GET_QOUTATION_BY_ID";
export const GET_QOUTATION_BY_ID_SUCCESS = "GET_QOUTATION_BY_ID_SUCCESS";
export const GET_QOUTATION_BY_ID_FAIL = "GET_QOUTATION_BY_ID_FAIL";

export const GET_QOUTATION_STEP1 = "GET_QOUTATION_STEP1";
export const GET_QOUTATION_STEP1_SUCCESS = "GET_QOUTATION_STEP1_SUCCESS";
export const GET_QOUTATION_STEP1_FAIL = "GET_QOUTATION_STEP1_FAIL";

