// src/store/places/actionTypes.js

export const GET_PLACES = "GET_PLACES";
export const GET_PLACES_SUCCESS = "GET_PLACES_SUCCESS";
export const GET_PLACES_FAIL = "GET_PLACES_FAIL";

export const GET_PLACE = "GET_PLACE";
export const GET_PLACE_SUCCESS = "GET_PLACE_SUCCESS";
export const GET_PLACE_FAIL = "GET_PLACE_FAIL";

export const CREATE_PLACE = "CREATE_PLACE";
export const CREATE_PLACE_SUCCESS = "CREATE_PLACE_SUCCESS";
export const CREATE_PLACE_FAIL = "CREATE_PLACE_FAIL";

export const UPDATE_PLACE = "UPDATE_PLACE";
export const UPDATE_PLACE_SUCCESS = "UPDATE_PLACE_SUCCESS";
export const UPDATE_PLACE_FAIL = "UPDATE_PLACE_FAIL";

export const DELETE_PLACE = "DELETE_PLACE";
export const DELETE_PLACE_SUCCESS = "DELETE_PLACE_SUCCESS";
export const DELETE_PLACE_FAIL = "DELETE_PLACE_FAIL";

export const CLEAR_PLACES_MESSAGES = "CLEAR_PLACES_MESSAGES";
