
// LIST / LOAD
export const GET_HR_RULES = "GET_HR_RULES";
export const GET_HR_RULES_SUCCESS = "GET_HR_RULES_SUCCESS";
export const GET_HR_RULES_FAIL = "GET_HR_RULES_FAIL";

// CREATE
export const CREATE_HR_RULE = "CREATE_HR_RULE";
export const CREATE_HR_RULE_SUCCESS = "CREATE_HR_RULE_SUCCESS";
export const CREATE_HR_RULE_FAIL = "CREATE_HR_RULE_FAIL";

// UPDATE
export const UPDATE_HR_RULE = "UPDATE_HR_RULE";
export const UPDATE_HR_RULE_SUCCESS = "UPDATE_HR_RULE_SUCCESS";
export const UPDATE_HR_RULE_FAIL = "UPDATE_HR_RULE_FAIL";

// DELETE
export const DELETE_HR_RULE = "DELETE_HR_RULE";
export const DELETE_HR_RULE_SUCCESS = "DELETE_HR_RULE_SUCCESS";
export const DELETE_HR_RULE_FAIL = "DELETE_HR_RULE_FAIL";