// src/store/hotels/actionTypes.js

// LIST
export const GET_HOTELS = "GET_HOTELS";
export const GET_HOTELS_SUCCESS = "GET_HOTELS_SUCCESS";
export const GET_HOTELS_FAIL = "GET_HOTELS_FAIL";

// CONTRACTS
export const GET_HOTEL_CONTRACTS = "GET_HOTEL_CONTRACTS";
export const GET_HOTEL_CONTRACTS_SUCCESS = "GET_HOTEL_CONTRACTS_SUCCESS";
export const GET_HOTEL_CONTRACTS_FAIL = "GET_HOTEL_CONTRACTS_FAIL";

export const CREATE_HOTEL_CONTRACT = "CREATE_HOTEL_CONTRACT";
export const CREATE_HOTEL_CONTRACT_SUCCESS = "CREATE_HOTEL_CONTRACT_SUCCESS";
export const CREATE_HOTEL_CONTRACT_FAIL = "CREATE_HOTEL_CONTRACT_FAIL";

export const UPDATE_HOTEL_CONTRACT = "UPDATE_HOTEL_CONTRACT";
export const UPDATE_HOTEL_CONTRACT_SUCCESS = "UPDATE_HOTEL_CONTRACT_SUCCESS";
export const UPDATE_HOTEL_CONTRACT_FAIL = "UPDATE_HOTEL_CONTRACT_FAIL";

export const DELETE_HOTEL_CONTRACT = "DELETE_HOTEL_CONTRACT";
export const DELETE_HOTEL_CONTRACT_SUCCESS = "DELETE_HOTEL_CONTRACT_SUCCESS";
export const DELETE_HOTEL_CONTRACT_FAIL = "DELETE_HOTEL_CONTRACT_FAIL";

// CONTRACT RATES (deprecated - kept for backward compatibility)
export const GET_HOTEL_CONTRACT_RATES = "GET_HOTEL_CONTRACT_RATES";
export const GET_HOTEL_CONTRACT_RATES_SUCCESS =
  "GET_HOTEL_CONTRACT_RATES_SUCCESS";
export const GET_HOTEL_CONTRACT_RATES_FAIL = "GET_HOTEL_CONTRACT_RATES_FAIL";

export const CREATE_HOTEL_CONTRACT_RATE = "CREATE_HOTEL_CONTRACT_RATE";
export const CREATE_HOTEL_CONTRACT_RATE_SUCCESS =
  "CREATE_HOTEL_CONTRACT_RATE_SUCCESS";
export const CREATE_HOTEL_CONTRACT_RATE_FAIL =
  "CREATE_HOTEL_CONTRACT_RATE_FAIL";

export const UPDATE_HOTEL_CONTRACT_RATE = "UPDATE_HOTEL_CONTRACT_RATE";
export const UPDATE_HOTEL_CONTRACT_RATE_SUCCESS =
  "UPDATE_HOTEL_CONTRACT_RATE_SUCCESS";
export const UPDATE_HOTEL_CONTRACT_RATE_FAIL =
  "UPDATE_HOTEL_CONTRACT_RATE_FAIL";

export const DELETE_HOTEL_CONTRACT_RATE = "DELETE_HOTEL_CONTRACT_RATE";
export const DELETE_HOTEL_CONTRACT_RATE_SUCCESS =
  "DELETE_HOTEL_CONTRACT_RATE_SUCCESS";
export const DELETE_HOTEL_CONTRACT_RATE_FAIL =
  "DELETE_HOTEL_CONTRACT_RATE_FAIL";

// SEASONS
export const GET_HOTEL_SEASONS = "GET_HOTEL_SEASONS";
export const GET_HOTEL_SEASONS_SUCCESS = "GET_HOTEL_SEASONS_SUCCESS";
export const GET_HOTEL_SEASONS_FAIL = "GET_HOTEL_SEASONS_FAIL";

export const CREATE_HOTEL_SEASON = "CREATE_HOTEL_SEASON";
export const CREATE_HOTEL_SEASON_SUCCESS = "CREATE_HOTEL_SEASON_SUCCESS";
export const CREATE_HOTEL_SEASON_FAIL = "CREATE_HOTEL_SEASON_FAIL";

export const UPDATE_HOTEL_SEASON = "UPDATE_HOTEL_SEASON";
export const UPDATE_HOTEL_SEASON_SUCCESS = "UPDATE_HOTEL_SEASON_SUCCESS";
export const UPDATE_HOTEL_SEASON_FAIL = "UPDATE_HOTEL_SEASON_FAIL";

export const DELETE_HOTEL_SEASON = "DELETE_HOTEL_SEASON";
export const DELETE_HOTEL_SEASON_SUCCESS = "DELETE_HOTEL_SEASON_SUCCESS";
export const DELETE_HOTEL_SEASON_FAIL = "DELETE_HOTEL_SEASON_FAIL";

// PRICING (Seasons with nested rates)
export const GET_HOTEL_SEASONS_WITH_RATES = "GET_HOTEL_SEASONS_WITH_RATES";
export const GET_HOTEL_SEASONS_WITH_RATES_SUCCESS =
  "GET_HOTEL_SEASONS_WITH_RATES_SUCCESS";
export const GET_HOTEL_SEASONS_WITH_RATES_FAIL =
  "GET_HOTEL_SEASONS_WITH_RATES_FAIL";

// NEW: SEASON RATES (rates live inside seasons)
export const CREATE_HOTEL_SEASON_RATE = "CREATE_HOTEL_SEASON_RATE";
export const CREATE_HOTEL_SEASON_RATE_SUCCESS =
  "CREATE_HOTEL_SEASON_RATE_SUCCESS";
export const CREATE_HOTEL_SEASON_RATE_FAIL = "CREATE_HOTEL_SEASON_RATE_FAIL";

export const UPDATE_HOTEL_SEASON_RATE = "UPDATE_HOTEL_SEASON_RATE";
export const UPDATE_HOTEL_SEASON_RATE_SUCCESS =
  "UPDATE_HOTEL_SEASON_RATE_SUCCESS";
export const UPDATE_HOTEL_SEASON_RATE_FAIL = "UPDATE_HOTEL_SEASON_RATE_FAIL";

export const DELETE_HOTEL_SEASON_RATE = "DELETE_HOTEL_SEASON_RATE";
export const DELETE_HOTEL_SEASON_RATE_SUCCESS =
  "DELETE_HOTEL_SEASON_RATE_SUCCESS";
export const DELETE_HOTEL_SEASON_RATE_FAIL = "DELETE_HOTEL_SEASON_RATE_FAIL";

export const CLEAR_HOTEL_SEASON_MESSAGES = "CLEAR_HOTEL_SEASON_MESSAGES";

// ADDITIONAL SERVICES
export const GET_HOTEL_ADDITIONAL_SERVICES = "GET_HOTEL_ADDITIONAL_SERVICES";
export const GET_HOTEL_ADDITIONAL_SERVICES_SUCCESS =
  "GET_HOTEL_ADDITIONAL_SERVICES_SUCCESS";
export const GET_HOTEL_ADDITIONAL_SERVICES_FAIL =
  "GET_HOTEL_ADDITIONAL_SERVICES_FAIL";

export const CREATE_HOTEL_ADDITIONAL_SERVICE =
  "CREATE_HOTEL_ADDITIONAL_SERVICE";
export const CREATE_HOTEL_ADDITIONAL_SERVICE_SUCCESS =
  "CREATE_HOTEL_ADDITIONAL_SERVICE_SUCCESS";
export const CREATE_HOTEL_ADDITIONAL_SERVICE_FAIL =
  "CREATE_HOTEL_ADDITIONAL_SERVICE_FAIL";

export const UPDATE_HOTEL_ADDITIONAL_SERVICE =
  "UPDATE_HOTEL_ADDITIONAL_SERVICE";
export const UPDATE_HOTEL_ADDITIONAL_SERVICE_SUCCESS =
  "UPDATE_HOTEL_ADDITIONAL_SERVICE_SUCCESS";
export const UPDATE_HOTEL_ADDITIONAL_SERVICE_FAIL =
  "UPDATE_HOTEL_ADDITIONAL_SERVICE_FAIL";

export const DELETE_HOTEL_ADDITIONAL_SERVICE =
  "DELETE_HOTEL_ADDITIONAL_SERVICE";
export const DELETE_HOTEL_ADDITIONAL_SERVICE_SUCCESS =
  "DELETE_HOTEL_ADDITIONAL_SERVICE_SUCCESS";
export const DELETE_HOTEL_ADDITIONAL_SERVICE_FAIL =
  "DELETE_HOTEL_ADDITIONAL_SERVICE_FAIL";
