// LIST
export const GET_HR_EMPLOYEES = "GET_HR_EMPLOYEES";
export const GET_HR_EMPLOYEES_SUCCESS = "GET_HR_EMPLOYEES_SUCCESS";
export const GET_HR_EMPLOYEES_FAIL = "GET_HR_EMPLOYEES_FAIL";

// ROLES
export const GET_HR_ROLES = "GET_HR_ROLES";
export const GET_HR_ROLES_SUCCESS = "GET_HR_ROLES_SUCCESS";
export const GET_HR_ROLES_FAIL = "GET_HR_ROLES_FAIL";

// CREATE
export const CREATE_HR_EMPLOYEE = "CREATE_HR_EMPLOYEE";
export const CREATE_HR_EMPLOYEE_SUCCESS = "CREATE_HR_EMPLOYEE_SUCCESS";
export const CREATE_HR_EMPLOYEE_FAIL = "CREATE_HR_EMPLOYEE_FAIL";

// UPDATE
export const GET_HR_EMPLOYEE_DETAIL = "GET_HR_EMPLOYEE_DETAIL";
export const GET_HR_EMPLOYEE_DETAIL_SUCCESS =
  "GET_HR_EMPLOYEE_DETAIL_SUCCESS";
export const GET_HR_EMPLOYEE_DETAIL_FAIL = "GET_HR_EMPLOYEE_DETAIL_FAIL";

export const UPDATE_HR_EMPLOYEE = "UPDATE_HR_EMPLOYEE";
export const UPDATE_HR_EMPLOYEE_SUCCESS = "UPDATE_HR_EMPLOYEE_SUCCESS";
export const UPDATE_HR_EMPLOYEE_FAIL = "UPDATE_HR_EMPLOYEE_FAIL";

export const RESET_HR_EMPLOYEE_FLAGS = "RESET_HR_EMPLOYEE_FLAGS";
