// LIST
export const GET_RESTAURANT_MEALS = "GET_RESTAURANT_MEALS";
export const GET_RESTAURANT_MEALS_SUCCESS = "GET_RESTAURANT_MEALS_SUCCESS";
export const GET_RESTAURANT_MEALS_FAIL = "GET_RESTAURANT_MEALS_FAIL";

// CRUD
export const CREATE_RESTAURANT_MEAL = "CREATE_RESTAURANT_MEAL";
export const CREATE_RESTAURANT_MEAL_SUCCESS = "CREATE_RESTAURANT_MEAL_SUCCESS";
export const CREATE_RESTAURANT_MEAL_FAIL = "CREATE_RESTAURANT_MEAL_FAIL";

export const UPDATE_RESTAURANT_MEAL = "UPDATE_RESTAURANT_MEAL";
export const UPDATE_RESTAURANT_MEAL_SUCCESS = "UPDATE_RESTAURANT_MEAL_SUCCESS";
export const UPDATE_RESTAURANT_MEAL_FAIL = "UPDATE_RESTAURANT_MEAL_FAIL";

export const DELETE_RESTAURANT_MEAL = "DELETE_RESTAURANT_MEAL";
export const DELETE_RESTAURANT_MEAL_SUCCESS = "DELETE_RESTAURANT_MEAL_SUCCESS";
export const DELETE_RESTAURANT_MEAL_FAIL = "DELETE_RESTAURANT_MEAL_FAIL";

// UI
export const CLEAR_RESTAURANT_MEALS_MESSAGES =
  "CLEAR_RESTAURANT_MEALS_MESSAGES";
