export const LOAD_MY_PERMISSIONS = "LOAD_MY_PERMISSIONS";
export const LOAD_MY_PERMISSIONS_SUCCESS = "LOAD_MY_PERMISSIONS_SUCCESS";
export const LOAD_MY_PERMISSIONS_ERROR = "LOAD_MY_PERMISSIONS_ERROR";
