export const GET_PLACE_ENTRANCE_FEES = "GET_PLACE_ENTRANCE_FEES";
export const GET_PLACE_ENTRANCE_FEES_SUCCESS =
  "GET_PLACE_ENTRANCE_FEES_SUCCESS";
export const GET_PLACE_ENTRANCE_FEES_FAIL = "GET_PLACE_ENTRANCE_FEES_FAIL";

export const CREATE_PLACE_ENTRANCE_FEES = "CREATE_PLACE_ENTRANCE_FEES";
export const CREATE_PLACE_ENTRANCE_FEES_SUCCESS =
  "CREATE_PLACE_ENTRANCE_FEES_SUCCESS";
export const CREATE_PLACE_ENTRANCE_FEES_FAIL =
  "CREATE_PLACE_ENTRANCE_FEES_FAIL";

export const UPDATE_PLACE_ENTRANCE_FEE = "UPDATE_PLACE_ENTRANCE_FEE";
export const UPDATE_PLACE_ENTRANCE_FEE_SUCCESS =
  "UPDATE_PLACE_ENTRANCE_FEE_SUCCESS";
export const UPDATE_PLACE_ENTRANCE_FEE_FAIL = "UPDATE_PLACE_ENTRANCE_FEE_FAIL";

export const DELETE_PLACE_ENTRANCE_FEE = "DELETE_PLACE_ENTRANCE_FEE";
export const DELETE_PLACE_ENTRANCE_FEE_SUCCESS =
  "DELETE_PLACE_ENTRANCE_FEE_SUCCESS";
export const DELETE_PLACE_ENTRANCE_FEE_FAIL = "DELETE_PLACE_ENTRANCE_FEE_FAIL";

export const CLEAR_PLACE_ENTRANCE_FEES_MESSAGES =
  "CLEAR_PLACE_ENTRANCE_FEES_MESSAGES";
